add_lunch_combo screwd_angler-userdebug
#add_lunch_combo screwd_bullhead-userdebug
#add_lunch_combo screwd_flo-userdebug
#add_lunch_combo screwd_hammerhead-userdebug
#add_lunch_combo screwd_marlin-userdebug
#add_lunch_combo screwd_sailfish-userdebug
#add_lunch_combo screwd_shamu-userdebug
