# Versioning System
PRODUCT_VERSION_MAJOR = 2
PRODUCT_VERSION_MINOR = 0
PRODUCT_VERSION_MAINTENANCE = alpha
ifdef SCREWD_BUILD_EXTRA
    SCREWD_POSTFIX := -$(SCREWD_BUILD_EXTRA)
endif
ifndef SCREWD_BUILD_TYPE
    SCREWD_BUILD_TYPE := alpha
    SCREWD_POSTFIX := $(shell date +"%Y%m%d")
endif

# Set all versions
SCREWD_VERSION := screwd-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR).$(PRODUCT_VERSION_MAINTENANCE)
SCREWD_MOD_VERSION := screwd-$(SCREWD_BUILD)-$(SCREWD_BUILD_TYPE).$(PRODUCT_VERSION_MAINTENANCE)-$(SCREWD_POSTFIX)

PRODUCT_PROPERTY_OVERRIDES += \
    BUILD_DISPLAY_ID=$(BUILD_ID) \
    ro.ota.version=$(PRODUCT_VERSION_MAJOR)-$(SCREWD_POSTFIX) \
    ro.screwd.version=$(SCREWD_VERSION) \
    ro.modversion=$(SCREWD_MOD_VERSION) \
    ro.screwd.buildtype=$(SCREWD_BUILD_TYPE)
